'use client'

import { useEffect, useState, ReactNode } from 'react'
import { IoInformationCircle } from 'react-icons/io5'
import { useTranslation } from '../context/LanguageContext'
import styles from '../styles/SummaryModal.module.css'

interface SummaryModalProps {
  isOpen: boolean
  onClose: () => void
  title: string
  content: Array<string | ReactNode>
}

const SummaryModal = ({ isOpen, onClose, title, content }: SummaryModalProps) => {
  const { t } = useTranslation()
  const [showTooltip, setShowTooltip] = useState(false)

  useEffect(() => {
    const handleEsc = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose()
    }

    if (isOpen) {
      document.addEventListener('keydown', handleEsc)
      document.body.style.overflow = 'hidden'
    }

    return () => {
      document.removeEventListener('keydown', handleEsc)
      document.body.style.overflow = 'unset'
    }
  }, [isOpen, onClose])

  if (!isOpen) return null

  return (
    <div 
      className={styles.modalOverlay} 
      onClick={onClose}
      role="dialog"
      aria-modal="true"
      aria-labelledby="summary-modal-title"
    >
      <div className={styles.modalContent} onClick={e => e.stopPropagation()}>
        <button className={styles.closeButton} onClick={onClose} aria-label={t('common.close', 'Close')}>
          ×
        </button>
        <h2 id="summary-modal-title">{title}</h2>
        {Array.isArray(content) ? (
          <ul>
            {content.map((item, index) => (
              <li key={index}>{item}</li>
            ))}
          </ul>
        ) : (
          <div>{content}</div>
        )}
        <div className={styles.modalFooter}>
          <div 
            className={styles.infoContainer}
            onMouseEnter={() => setShowTooltip(true)}
            onMouseLeave={() => setShowTooltip(false)}
          >
            <IoInformationCircle className={styles.infoIcon} aria-hidden="true" />
            {showTooltip && (
              <div className={styles.infoTooltip} role="note">
                {t('common.aiGeneratedSummary', 'This summary was generated by AI based on the information in my CV.')}
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  )
}

export default SummaryModal


