'use client'

import { useState } from 'react'
import { useEffect } from 'react'
import { IoInformationCircle } from 'react-icons/io5'
import styles from '../styles/SummaryModal.module.css'

const SummaryModal = ({ isOpen, onClose, title, content }) => {
  const [showTooltip, setShowTooltip] = useState(false)

  useEffect(() => {
    const handleEsc = (e) => {
      if (e.key === 'Escape') onClose()
    }
    
    if (isOpen) {
      document.addEventListener('keydown', handleEsc)
      document.body.style.overflow = 'hidden'
    }

    return () => {
      document.removeEventListener('keydown', handleEsc)
      document.body.style.overflow = 'unset'
    }
  }, [isOpen, onClose])

  if (!isOpen) return null

  return (
    <div className={styles.modalOverlay} onClick={onClose}>
      <div className={styles.modalContent} onClick={e => e.stopPropagation()}>
        <button className={styles.closeButton} onClick={onClose}>×</button>
        <h2>{title}</h2>
        <ul>
          {content.map((item, index) => (
            <li key={index}>{item}</li>
          ))}
        </ul>
        <div className={styles.modalFooter}>
          <div 
            className={styles.infoContainer}
            onMouseEnter={() => setShowTooltip(true)}
            onMouseLeave={() => setShowTooltip(false)}
          >
            <IoInformationCircle className={styles.infoIcon} />
            {showTooltip && (
              <div className={styles.infoTooltip}>
                This summary was generated by AI based on the information in my CV.
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  )
}

export default SummaryModal 